# Generated by Django 5.2 on 2025-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('Music', 'Музыка'), ('Sport', 'Спорт'), ('Film', 'Фильм'), ('Other', 'Другое')], default='Other', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
